language: python

matrix:
  include:
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="all"       PYSMT_GMPY="TRUE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="all"       PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="TRUE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="msat"      PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="z3"        PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="cvc4"      PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="yices"     PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="bdd"       PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="picosat"   PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="btor"      PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="msat_wrap" PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 3.6
  #   env: PYSMT_SOLVER="z3_wrap"   PYSMT_GMPY="FALSE"

  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="all"       PYSMT_GMPY="TRUE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="all"       PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="TRUE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="msat"      PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="z3"        PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="cvc4"      PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="yices"     PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="bdd"       PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="picosat"   PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="btor"      PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="msat_wrap" PYSMT_GMPY="FALSE"
  # - os: linux
  #   python: 2.7
  #   env: PYSMT_SOLVER="z3_wrap"   PYSMT_GMPY="FALSE"

  # - os: linux
  #   python: pypy
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="TRUE"
  # - os: linux
  #   python: pypy
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="FALSE"

  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="all"       PYSMT_GMPY="TRUE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="all"       PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="TRUE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="msat"      PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  - os: osx
    osx_image: xcode9.3
    language: generic
    python: 3.6
    env: PYSMT_SOLVER="z3"        PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="cvc4"      PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="yices"     PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="bdd"       PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="picosat"   PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="btor"      PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="msat_wrap" PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 3.6
  #   env: PYSMT_SOLVER="z3_wrap"   PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="3.6.5"

  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="all"       PYSMT_GMPY="TRUE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="all"       PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="TRUE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="msat"      PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="z3"        PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="cvc4"      PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="yices"     PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="bdd"       PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="picosat"   PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="btor"      PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="msat_wrap" PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: 2.7
  #   env: PYSMT_SOLVER="z3_wrap"   PYSMT_GMPY="FALSE"   TRAVIS_PYTHON_VERSION="2.7.15"

  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: pypy
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="TRUE"   TRAVIS_PYTHON_VERSION="pypy"
  # - os: osx
  #   osx_image: xcode9.3
  #   language: generic
  #   python: pypy
  #   env: PYSMT_SOLVER="None"      PYSMT_GMPY="FALSE"   PYSMT_CYTHON="FALSE"   TRAVIS_PYTHON_VERSION="pypy"


git:
  depth: 10

cache:
  apt: true
  directories:
  - ${HOME}/.smt_solvers/btor
  - ${HOME}/.smt_solvers/bdd
  - ${HOME}/.cache/pip
  - ${HOME}/python_bindings/all
  - ${HOME}/python_bindings/msat
  - ${HOME}/python_bindings/z3
  - ${HOME}/python_bindings/cvc4
  - ${HOME}/python_bindings/yices
  - ${HOME}/python_bindings/bdd
  - ${HOME}/python_bindings/picosat
  - ${HOME}/python_bindings/btor

addons:
  apt:
    packages:
    - python-setuptools
    - python-nose
    - python-pip
    - python-dev
    - make
    - build-essential
    - swig
    - libgmp-dev
    - autoconf
    - libtool
    - wget
    - curl
    - libboost-dev
    - python3-all-dev
    - libmpc-dev

before_install: |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    brew update
    # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
    brew install openssl readline swig
    # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
    # I didn't do this above because it works and I'm lazy.
    brew outdated pyenv || brew upgrade pyenv
    # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
    # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
    brew install pyenv-virtualenv
    pyenv install ${TRAVIS_PYTHON_VERSION}
    # I would expect something like ``pyenv init; pyenv local ${TRAVIS_PYTHON_VERSION}`` or
    # ``pyenv shell ${TRAVIS_PYTHON_VERSION}` would work, but ``pyenv init`` doesn't seem to
    # modify the Bash environment. ??? So, I hand-set the variables instead.
    export PYENV_VERSION=${TRAVIS_PYTHON_VERSION}
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
  fi

install:
  - "./ci/travis_install.sh"

script:
  - "./ci/travis_script.sh"

after_success: |
  if [ "${TRAVIS_OS_NAME}" == "linux" ]; then coveralls; fi
